Add .editorconfig file
phylum-dev/cli pull request #1191
Opened 2023-08-15 16:58 UTC by kylewillmon

Close #1154

2023-08-15 16:59 UTC, kylewillmon commented on .editorconfig
> +max_line_length = 80
I picked 80 to match the limit currently being enforced on `extensions/**/*.md` by `deno fmt`.

2023-08-15 17:06 UTC, cd-work approved these changes

2023-08-15 23:36 UTC, maxrake requested changes
The `.editorconfig` solution proposed in this PR is not functional with VS Code. At least, personal trial and error has not resulted in a configuration that works to format markdown files with VS Code and the `prettier` extension.

This PR _may_ be okay on it's own but it should not be linked to #1154 for closing since that is a spike/research issue that states:

> The desired end state is a solution reached through consensus, but not implemented. Implementation will happen in a different issue, assuming there is a solution that requires changes.

There are other goals (e.g., enforcement and standards documentation) that should also be addressed within the spike ticket before any implementation is brought forward. Basically, the request here is to propose solutions in #1154 and complete that issue before bringing forward any PRs related to it.

2023-08-16 16:31 UTC, kylewillmon commented
> The `.editorconfig` solution proposed in this PR is not functional with VS Code. At least, personal trial and error has not resulted in a configuration that works to format markdown files with VS Code and the `prettier` extension.

That is because `prettier` does not wrap prose in Markdown by default. And configuring the extension with `"prettier.proseWrap": "always"` does not help because the extension sees that we have an `.editorconfig` file and ignores the extension config (as seen in line from the extension log):

```
["INFO" - 10:53:51 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
```

So to get prettier to wrap prose from the VS Code extension, we would need to add a `.prettierrc` file containing `{"proseWrap": "always"}` to the root of the repo.

But even that has major issues... Because `prettier` only supports formatting entire documents (for Markdown, at least). And the goal of using `.editorconfig` was to **avoid** locking developers into a specific tool.

So I think we have no choice but to give `prettier` the boot on this.

As an alternative for VS Code, I would recommend adding `"[markdown]": { "editor.rulers": [80] }` to your config to give a visual indication. The editorconfig extension has plans to add this automatically (See editorconfig/editorconfig-vscode#272), but that is not yet done.

And, to supplement, the [Rewrap extension](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) can wrap to a ruler.

These solutions are annoyingly complicated... But that is because VS Code has made this complicated... Other editors do not have this issue and we can't let the choices of a single editor slow us down.

2023-08-16 16:40 UTC, kylewillmon commented
> This PR _may_ be okay on it's own but it should not be linked to #1154

I have removed the link

2023-08-16 16:51 UTC, maxrake approved these changes
The VS Code integration complication is a shame. Visual rulers are in place now, which does help a bit. LGTM.

2023-08-16 16:52 UTC, merged