Add selfmanage feature to xtask
phylum-dev/cli pull request #1197
Opened 2023-08-16 18:45 UTC by kylewillmon

Fix #965 by adding a `selfmanage` feature to `xtask`. This allows generating completion files with or without the `selfmanage` commands.

### With selfmanage (default)
```
cargo run -p xtask -- gencomp
```

### Without selfmanage
```
cargo run -p xtask --no-default-features -- gencomp
```

2023-08-16 19:13 UTC, maxrake approved these changes
Since this is a bugfix, a CHANGELOG entry was expected.

2023-08-16 19:29 UTC, maxrake submitted a review, later dismissed
LGTM

2023-08-16 21:10 UTC, cd-work requested changes

2023-08-16 21:10 UTC, cd-work commented on CHANGELOG.md
> +- Disabled selfmanage commands in completion for Homebrew users
"selfmanage commands" is internal terminology, so imo not ideal for a changelog entry.

2023-08-17 18:20 UTC, cd-work approved these changes

2023-08-17 18:21 UTC, merged