Don't print package with no active rejections
phylum-dev/cli pull request #1221
Opened 2023-08-30 22:01 UTC by kylewillmon

Packages with all rejections suppressed should not be displayed in the output report. This patch corrects the filter to account for that.

2023-08-30 22:04 UTC, cd-work requested changes

2023-08-30 22:04 UTC, cd-work commented on CHANGELOG.md
> +- Package header printed even when all issues were suppressed
This will be put in the wrong location once you rebase.

2023-08-30 23:10 UTC, maxrake requested changes
The changes were tested locally and appear to work for `phylum-ci`, which has a single package that has been suppressed (er..."allowed policy violation" now?)

<img width="1083" alt="image" src="https://github.com/phylum-dev/cli/assets/18729796/f513376f-be7e-4b63-bd75-e6fa6ea8a95b">

---

However, the output does not quite look right for testing with this (`cli`) repo, which currently has four (4) packages with policy violations:

<img width="893" alt="image" src="https://github.com/phylum-dev/cli/assets/18729796/dbf68899-bdd3-4b6c-9943-28fd7663f634">

<img width="1146" alt="image" src="https://github.com/phylum-dev/cli/assets/18729796/90fd3a97-ca03-402e-b78e-810f62e1cf29">

It appears the packages with a vulnerability issue were retained while the others were filtered out. Or, maybe it is that the packages with malicious issues were filtered out. Perhaps there is another bug here...

2023-08-30 23:19 UTC, kylewillmon commented
> Perhaps there is another bug here...

That is clearly a separate issue as they don't show up in either output in your screenshot. So they are not affected by this change.

2023-08-30 23:27 UTC, maxrake commented
> That is clearly a separate issue as they don't show up in either output in your screenshot.

The first output for the `cli` repo analysis, using the currently released version of the Phylum CLI includes the `md4@0.10.2` and `unicode-id@0.3.3` packages whereas the second output, using the changes from this PR, do not.

It still may be an unrelated bug...

2023-08-31 16:09 UTC, kylewillmon commented
> The first output for the `cli` repo analysis, using the currently released version of the Phylum CLI includes the `md4@0.10.2` and `unicode-id@0.3.3` packages whereas the second output, using the changes from this PR, do not.

Right. The package name is printed. But the issue (or rejection) is not. So the output is unhelpful. That is exactly what this PR fixes.

If (as you claim) there are issues missing that should be printed, that is an unrelated issue.

2023-08-31 17:59 UTC, maxrake commented
Oooh...I get it now 🐢
I'll look into this behavior a bit more and create a different issue for it.

2023-08-31 18:09 UTC, maxrake approved these changes
LGTM

2023-08-31 20:15 UTC, cd-work approved these changes

2023-08-31 20:15 UTC, merged