Switch to dependency file terminology
phylum-dev/cli pull request #1310
Opened 2023-12-04 20:00 UTC by cd-work

This patch makes sweeping breaking changes to change the internal and
public terminology to refer to a manifest or lockfile as "dependency
file".

This change should also clarify some CLI interfaces where the previous
terminology was asking for a lockfile, but a manifest file was accepted
without clearly stating it.

Closes https://github.com/phylum-dev/cli/issues/1271.

---

Currently there's two major unsolved things I'm aware of:
 - Types in `phylum_types` are not changed, this might be a good opportunity to get rid of it where possible since deprecation is planned?
 - `LockfileFormat` enum is unchanged, this makes some sense to me since the format is still about one specific lockfile type, but I did change the public CLI interface and some internal code to refer to it as "dependency file type"

2023-12-04 23:44 UTC, kylewillmon commented
> Types in phylum_types are not changed, this might be a good opportunity to get rid of it where possible since deprecation is planned?

I agree. Any types needed for CLI can (and should) be moved to this repo. If we find that they still need to be shared (which I doubt in most cases), they can be exported from here

2023-12-04 23:53 UTC, kylewillmon commented
> `LockfileFormat` enum is unchanged, this makes some sense to me since the format is still about one specific lockfile type, but I did change the public CLI interface and some internal code to refer to it as \"dependency file type\"

This seems reasonable and matches with our system of matching all manifest formats to a single associated lockfile format.

2023-12-05 20:48 UTC, maxrake requested changes
Full review coming...but wanted to at least point out the missing CHANGELOG entry for this breaking change...which will likely result in a v6.0.0 major version release.

2023-12-05 20:48 UTC, maxrake commented on .phylum_project
> +group_name: null
This looks like a `phylum init` was done locally, without the `--group integrations` option, and then committed. Changing the project to not have a group will remove the visibility previously enjoyed by everyone in the `integrations` group.

Now...changing the group to something else is another story...and may be warranted now.

2023-12-06 18:52 UTC, maxrake requested changes
Do we want to rename the `phylum_lockfile` package now?

2023-12-06 19:03 UTC, maxrake commented on extensions/phylum.ts
> +   *   { name: "accepts", version: "1.3.8", type: "npm", origin: "/path/to/lockfile" },
```suggestion
   *   { name: "accepts", version: "1.3.8", type: "npm", origin: "/path/to/dependency.file" },
```

2023-12-06 23:29 UTC, maxrake commented on docs/commands/phylum_analyze.md
After the changes, there are still two files that contain instances of `--lockfile`:

* `doc_templates/phylum_analyze.md`
* `doc_templates/phylum_package.md`

2023-12-06 23:33 UTC, cd-work commented on docs/commands/phylum_analyze.md
The `phylum_package` docs were actually *completely* broken. I think there might have been a copy/paste issue.

2023-12-07 17:18 UTC, maxrake requested changes
A few issues were created to follow up with the primary consumers of the CLI and it's extension API:

* https://github.com/phylum-dev/community-extensions/issues/29
* https://github.com/phylum-dev/phylum-ci/issues/363

There may still be changes needed in the `phylum-dev/documentation` repository.

2023-12-07 19:25 UTC, maxrake requested changes
Almost there...

2023-12-07 19:25 UTC, maxrake commented on CHANGELOG.md
The new entries in this file should be in the `Unreleased` section.

2023-12-07 19:25 UTC, maxrake commented on extensions/CHANGELOG.md
The new entries in this file should be in the `Unreleased` section.

2023-12-07 19:25 UTC, maxrake commented on extensions/CHANGELOG.md
> +- Changed `PhylumApi::analyze` packages type `PhylumApi::PackageWithOrigin`
```suggestion
- Changed `PhylumApi::analyze` packages type to `PhylumApi::PackageWithOrigin`
```

2023-12-07 20:42 UTC, maxrake requested changes
The `extensions/CHANGELOG.md` still has the new entries in the v5.9.0 section instead of the "Unreleased" section.

2023-12-07 21:16 UTC, maxrake approved these changes
LGTM

2023-12-07 21:39 UTC, merged