Move submit package API types to CLI and add vuln data.
phylum-dev/cli pull request #1314
Opened 2023-12-07 02:01 UTC by mathew-horner

In favor of https://github.com/phylum-dev/phylum-types/pull/86, I've moved the `SubmitPackageResponse` and all its child types from `phylum-types` to CLI. I've updated any other code that was referencing these types to the local instances.

Unfortunately a couple `From` impls were necessary to maintain compatibility with the code that still is using `PackageStatusExtended`... I guess I could move that too, but I didn't because it's out of scope for the main purpose of this PR.

closes https://github.com/phylum-dev/cli/issues/1313

2023-12-07 02:05 UTC, mathew-horner commented on cli/src/types.rs
> +/// Response body for `/data/packages/submit`.
I touched up some of these doc comments and removed ones that seemed redundant... lmk what you think.

2023-12-07 02:05 UTC, mathew-horner commented on cli/src/types.rs
> -        );
This test seemed unnecessary. The way `Ord` works is very well defined.

2023-12-07 02:08 UTC, mathew-horner commented
In order to test these changes, you'll need to point your CLI at staging. The API changes have not been cut to prod yet (deserialization will still succeed since it's an optional field, you just won't see it).

2023-12-08 21:04 UTC, kylewillmon requested changes

2023-12-08 23:09 UTC, kylewillmon approved these changes

2023-12-08 23:22 UTC, merged