Switch webserver to axum
phylum-dev/cli pull request #1432
Opened 2024-05-28 18:04 UTC by cd-work

This changes the internal webserver from the routerify crate to axum, since routerify is not maintained and pulls in a rather old hyper version.

2024-06-03 16:01 UTC, kylewillmon requested changes

2024-06-04 06:27 UTC, cd-work commented on cli/src/auth/server.rs
> +    let (send_shutdown, mut receive_shutdown) = mpsc::channel(4);
Just a random power of 2 that is larger than 3, to avoid hanging under normal operation. I can try and switch to `Notify`.

2024-06-04 06:41 UTC, cd-work commented on cli/src/auth/server.rs
> +    // log::debug!("Oauth server has called redirect uri: {}", request.uri());
I intentionally didn't add this because it's not worth it imo. But I've added it in the latest commit if you think there's value in it.

2024-06-04 14:10 UTC, kylewillmon approved these changes

2024-06-04 14:48 UTC, merged