Create directory with mode 700 by default
phylum-dev/cli pull request #289
Opened 2022-04-22 18:15 UTC by cd-work

Following the XDG spec, new directories will now be created with the
mode 700 set instead of 755.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

> If, when attempting to write a file, the destination directory is
> non-existent an attempt should be made to create it with permission
> 0700. If the destination directory exists already the permissions
> should not be changed. The application should be prepared to handle
> the case where the file could not be written, either because the
> directory was non-existent and could not be created, or for any other
> reason. In such case it may choose to present an error message to the
> user.

Closes #285.

2022-04-22 19:09 UTC, kylewillmon requested changes
This solves the issue for the bin and data directories (i.e., `~/.local/bin/` and `~/.local/share/phylum`, respectively), but not for the config directory (`~/.config/phylum`) which is created in `config.rs` (either [here](https://github.com/phylum-dev/cli/blob/432e4e7829c90b20a011996ae4b582b570ab783d/cli/src/config.rs#L100) or [here](https://github.com/phylum-dev/cli/blob/432e4e7829c90b20a011996ae4b582b570ab783d/cli/src/config.rs#L182) depending on the scenario).

2022-04-22 19:15 UTC, cd-work commented
> This solves the issue for the bin and data directories (i.e., ~/.local/bin/ and ~/.local/share/phylum, respectively), but not for the config directory (~/.config/phylum) which is created in config.rs (either here or here depending on the scenario).

I've set it for the case where the config directory is created by the `phylum` CLI. I don't think we should bother with it when the user manually created that directory.

2022-04-22 21:24 UTC, kylewillmon commented
> I've set it for the case where the config directory is created by the phylum CLI. I don't think we should bother with it when the user manually created that directory.

I agree that we shouldn't change the permissions if the user manually created the directory. The other case I linked is the `save_config` function, which is what creates the config directory in the fresh install case.

2022-04-22 22:27 UTC, maxrake reviewed
Missed in the first review...but two nits for `cli/src/install.sh`:

* This comment does not match the code (should be `zshrc`):

  ```sh
      # Remove old entries from bashrc.
      sed -i'' "/^fpath+=(\"\$HOME\/.phylum\/completions\")$/d" "${HOME}/.zshrc"
      sed -i'' "/^export PATH=\"\$HOME\/.phylum:\$PATH\"$/d" "${HOME}/.zshrc"
      sed -i'' "/^alias ph='phylum'$/d" "${HOME}/.zshrc"
  ```

* The `config_dir` variable on line 10 is unused:
  * `config_dir="${XDG_CONFIG_HOME:-${HOME}/.config}/phylum"`
  * Maybe this was left on purpose, to point out where the config is located since it's not otherwise obvious in this script

2022-04-25 15:47 UTC, maxrake submitted a review, later dismissed
My nits were fixed...thanks!

I'm sure you are already aware...but marking as needs changes since it doesn't build on Windows.

2022-04-25 16:24 UTC, kylewillmon approved these changes

2022-04-25 16:26 UTC, kylewillmon approved these changes

2022-04-25 16:42 UTC, merged