Fix yarn lockfile with unknown resolvers
phylum-dev/cli pull request #345
Opened 2022-05-04 18:37 UTC by cd-work

The yarn lockfile allows various different resolvers other than the
standard one which pulls from npm. Some of these include the filesystem
(@workspace), http/s (@http/s), and ssh (@ssh).

To ensure our parser is robust against all types of possible resolvers,
this patch checks for the presence of `@npm` to ensure that the
dependency can be resolved through npm. All other dependencies are
silently ignored.

This comes with the trade-off that it is easier for a failure to parse a
dependency, that can be resolved through npm, to be hidden from the
user, opening up the possibility for hidden vulnerabilities. It also
assumes that no package scope starts with `@npm`, otherwise the parser
might throw an error.

Closes #344.

2022-05-04 18:42 UTC, louislang submitted a review, later dismissed

2022-05-04 18:49 UTC, matt-phylum approved these changes

2022-05-04 19:19 UTC, kylewillmon requested changes
At a minimum, I think we need to print a warning for any packages that we ignore.

I've put additional concerns on the related issue (#344)

2022-05-05 20:21 UTC, kylewillmon submitted a review, later dismissed

2022-05-05 20:23 UTC, kylewillmon commented on cli/src/lockfiles/javascript.rs
> +                    None => return Err(anyhow!("Failed to parse yarn patch dependency")),
Some context here might be good.

```suggestion
                    None => return Err(anyhow!("Failed to parse yarn patch dependency for package '{}'", name)),
```

2022-05-05 20:32 UTC, kylewillmon approved these changes

2022-05-05 20:44 UTC, merged