`phylum auth set-token`
phylum-dev/cli pull request #786
Opened 2022-10-27 21:21 UTC by kylewillmon

This patch adds a command to set the token in the config file. This provides an alternative to `phylum auth login` provided you can get the token from some other place. The other place may be `phylum auth token` from another machine or, in the future, we may support copying the token directly from the web UI.

2022-10-27 21:59 UTC, furi0us333 requested changes
We should update the docs for this new subcommand

2022-10-28 12:13 UTC, andreaphylum approved these changes

2022-10-28 12:13 UTC, andreaphylum commented on cli/src/commands/auth.rs
> +    match matches.subcommand() {
I always like it when `if` chains become `match` blocks. 💯

2022-10-28 20:26 UTC, maxrake approved these changes
The behavior was confirmed with a local build and tested with both a token provided as an option and one provided from stdin. Other than adding documentation, LGTM.

2022-11-02 15:26 UTC, maxrake approved these changes

2022-11-02 15:47 UTC, furi0us333 approved these changes
LGTM

2022-11-02 17:05 UTC, maxrake requested changes
The new link or the new doc filename needs to change.

2022-11-02 17:05 UTC, maxrake commented on docs/command_line_tool/phylum_auth.md
> +* [phylum auth set-token](https://docs.phylum.io/docs/phylum_auth_set-token)
```suggestion
* [phylum auth set-token](https://docs.phylum.io/docs/phylum_auth_set_token)
```
The other possibility is to change the file name to `docs/command_line_tool/phylum_auth_set-token.md`...which would match the other command/page with a hyphenated name: `docs/command_line_tool/phylum_project_set-thresholds.md`

The working assumption here is the file name is what creates the page URL/slug.

2022-11-02 17:21 UTC, maxrake approved these changes

2022-11-02 21:45 UTC, cd-work submitted a review, later dismissed

2022-11-03 15:05 UTC, cd-work approved these changes

2022-11-03 15:42 UTC, merged