Add `--lockfile-type` option to `phylum analyze`
phylum-dev/cli pull request #798
Opened 2022-11-02 21:15 UTC by cd-work

This patch unifies the lockfile parser and enables passing the desired lockfile for all subcommands requiring lockfile parsing as an optional parameter.

Closes #794.

2022-11-02 22:15 UTC, maxrake requested changes
The changes in this PR were confirmed with local testing. It might still be good for someone else to look more closely at the Rust code.

Some observations:

```
# Rename a poetry lockfile to look like a yarn lockfile
../phylum-ci  7  22 on  main [!?] is 📦 v0.17.1 via 🐍 v3.11.0rc2 took 3s
❯ cp poetry.lock yarn.lock

# Rename a poetry lockfile to something that is not normal/recognized
../phylum-ci  7  22 on  main [!?] is 📦 v0.17.1 via 🐍 v3.11.0rc2 took 3s
❯ cp poetry.lock not_poetry.luck

# The following command does what is expected
../phylum-ci  7  23 on  main [!?] is 📦 v0.17.1 via 🐍 v3.11.0rc2
❯ /Users/maxrake/dev/phylum/localdev/cli/target/debug/phylum analyze --label type_test --lockfile-type yarn --verbose yarn.lock
[2022-11-02T22:03:53Z INFO  phylum_cli::config] Found project configuration file at ./.phylum_project
❗ Error: Unable to locate any valid package in package lockfile

Caused by:
    0: Failed to parse yarn lock file
    1: 0: at line 3, in TakeUntil:
       version = "22.1.0"
       ^

       1: at line 3, in name:
       version = "22.1.0"
       ^

       2: at line 3, in entry:
       version = "22.1.0"
       ^

       3: at line 3, in Many1:
       version = "22.1.0"
       ^

# The following command fails when it was expected to pass
../phylum-ci  7  23 on  main [!?] is 📦 v0.17.1 via 🐍 v3.11.0rc2 took 2s
✖ 1 ❯ /Users/maxrake/dev/phylum/localdev/cli/target/debug/phylum analyze --label type_test --lockfile-type poetry --verbose yarn.lock
[2022-11-02T22:05:33Z INFO  phylum_cli::config] Found project configuration file at ./.phylum_project
❗ Error: Unable to locate any valid package in package lockfile

Caused by:
    0: Failed to parse yarn lock file
    1: 0: at line 3, in TakeUntil:
       version = "22.1.0"
       ^

       1: at line 3, in name:
       version = "22.1.0"
       ^

       2: at line 3, in entry:
       version = "22.1.0"
       ^

       3: at line 3, in Many1:
       version = "22.1.0"
       ^

# The following command parses the lockfile as expected
../phylum-ci  7  23 on  main [!?] is 📦 v0.17.1 via 🐍 v3.11.0rc2 took 2s
✖ 1 ❯ /Users/maxrake/dev/phylum/localdev/cli/target/debug/phylum analyze --label type_test --lockfile-type poetry --verbose not_poetry.luck
[2022-11-02T22:08:02Z INFO  phylum_cli::config] Found project configuration file at ./.phylum_project
[2022-11-02T22:08:02Z INFO  phylum_cli::commands::parse] Identified lockfile type: poetry
✅ Succesfully parsed lockfile as type: poetry
✅ Job ID: 845c7e65-d07b-4747-9ed7-9a2f4f3e6ef5


          Project: phylum-ci                                               Label: type_test
---TRIMMED---

# The following command parses the lockfile as poetry even though yarn was provided as the type. Some extra/better log messages would help here, to inform the user of the mis-match/failure and how it was auto detected
../phylum-ci  7  23 on  main [!?] is 📦 v0.17.1 via 🐍 v3.11.0rc2 took 3s
❯ /Users/maxrake/dev/phylum/localdev/cli/target/debug/phylum analyze --label type_test --lockfile-type yarn --verbose not_poetry.luck
[2022-11-02T22:08:25Z INFO  phylum_cli::config] Found project configuration file at ./.phylum_project
[2022-11-02T22:08:25Z INFO  phylum_cli::commands::parse] Identified lockfile type: poetry
✅ Succesfully parsed lockfile as type: poetry
✅ Job ID: 823ded5f-3d58-4c14-ac14-f4eb8c7fc407


          Project: phylum-ci                                               Label: type_test
---TRIMMED---
```

`docs/command_line_tool/phylum_analyze.md` needs to be updated to include the new option...to be like `docs/command_line_tool/phylum_parse.md`.

Also, while not directly related to this PR, a typo in `cli/src/commands/jobs.rs` was noticed in a message during testing:
* `Succesfully parsed lockfile as type:` should be `Successfully parsed lockfile as type:` (one more `s` to be successful)

2022-11-03 14:28 UTC, kylewillmon requested changes

2022-11-03 17:37 UTC, kylewillmon submitted a review, later dismissed

2022-11-03 20:06 UTC, maxrake requested changes
`docs/command_line_tool/phylum_analyze.md` needs to be updated to include the new option...to be like `docs/command_line_tool/phylum_parse.md`.

Also, while not directly related to this PR, a typo in `cli/src/commands/jobs.rs` was noticed in a message during testing:
* `Succesfully parsed lockfile as type:` should be `Successfully parsed lockfile as type:` (one more `s` to be successful)

2022-11-03 20:14 UTC, maxrake approved these changes
Behavior was confirmed with local testing. LGTM.

2022-11-03 20:37 UTC, merged