update phylum-types
phylum-dev/cli pull request #805
Opened 2022-11-10 17:25 UTC by JosephPhylum

update phylum-types to support "phylum package -t cargo" previously it was expecting -t rust, which is inconsistent with the rest of the options, and inconsistent with the help description. 

## Checklist

- [ ] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?
- [ ] Have you ensured that you have met the expected acceptance criteria?
- [ ] Have you created sufficient tests?
- [ ] Have you updated all affected documentation?

2022-11-10 17:41 UTC, kylewillmon commented
> update phylum-types to support "phylum package -t cargo" previously it was expecting -t rust, which is inconsistent with the rest of the options, and inconsistent with the help description.

`phylum package -t cargo` is also inconsistent with the rest of the options... Here are the current options (from the help output)

```
  -t, --package-type <type>  The type of the package ("npm", "rubygems", "pypi", "maven", "nuget", "golang", "cargo")
```

As can be seen, the existing options refer to the registry on which the package resides:

* `npm` -> `npmjs.org`
* `rubygems` -> `rubygems.org`
* `pypi` -> `pypi.org`
* `maven` -> `maven.org`
* `nuget` -> `nuget.org`

It makes sense to refer to the registry because that is where a given package name and version can be resolved. Outside of a registry (or even inside of a poorly designed registry...), there may be multiple packages with the same name and version.

The new options of `golang` and `cargo` do not follow this trend. To follow the trend, these should probably be `go` (for `go.dev`) and `crates-io` (for `crates.io`) or something to that effect.

2022-11-10 17:41 UTC, kylewillmon requested changes
The new behavior matches the help output, but is still inconsistent with other package types.

2022-11-10 18:07 UTC, ejortega commented
> The new behavior matches the help output, but is still inconsistent with other package types.

I believe @JosephPhylum was just following https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst which `rubygems` doesn't follow.

Do we want to update the ecosystem name as well to reflect the registry?

@louislang @furi0us333

2022-11-10 18:13 UTC, furi0us333 commented
My understanding is that we were going to try and follow purl, will leave that to @louislang for the final decision

2022-11-10 18:15 UTC, louislang commented
I totally see the logic in using `go` and `cargo-io`, but lets standardize on purl across the platform.

2022-11-10 19:32 UTC, kylewillmon commented
That makes sense and it is fortunate that we already use most of the correct names for PURL.

The only exception is `rubygems` should be `gem`. Is there a ticket somewhere to track that switch? If not, I will create one.

2022-11-10 19:32 UTC, kylewillmon approved these changes

2022-11-10 19:35 UTC, merged

2022-11-11 01:46 UTC, louislang commented
I don't think we've got a ticket tracking that. We should definitely make one @kylewillmon!

2022-11-11 01:49 UTC, kylewillmon commented
Done. phylum-dev/phylum-types#61