docs: Update Welcome page and add to VCS
phylum-dev/cli pull request #846
Opened 2022-12-01 21:40 UTC by furi0us333

- Implementing changes to the Welcome page and bringing that page into VCS
- Add supporting animations to the `assets` folder

2022-12-01 22:02 UTC, cd-work requested changes

2022-12-02 22:26 UTC, furi0us333 commented on docs/welcome/welcome.md
> +- [Submit your package lock file](https://docs.phylum.io/docs/phylum_analyze) (`phylum analyze <package-lock-file.ext>`)
Will publish as is today, but plan to update with `phylum init` shortly as I get familiar with it.

2022-12-02 22:27 UTC, furi0us333 commented on docs/welcome/welcome.md
> +- https://blog.phylum.io/insights-and-resources/pick-a-python-lockfile-and-improve-security
Relocated closer to the analyze command as that is where it is important to understand lockfiles (the reason they marketing wanted this post added)

2022-12-02 22:27 UTC, furi0us333 commented on docs/welcome/welcome.md
> +## Analyze Your First Project
Agreed, removed the first section in favor of the complete walkthrough

2022-12-02 22:28 UTC, furi0us333 commented on docs/welcome/welcome.md
> +curl <https://sh.phylum.io> | sh
Removed

2022-12-02 22:28 UTC, furi0us333 commented on docs/welcome/welcome.md
> +![Create Project](https://raw.githubusercontent.com/phylum-dev/cli/main/assets/create-project.webp)
Will update to `phylum init` soon

2022-12-02 22:28 UTC, furi0us333 commented on docs/welcome/welcome.md
> +### Analyze a Project
Updated

2022-12-02 22:29 UTC, furi0us333 commented on docs/welcome/welcome.md
> +![View Results](https://raw.githubusercontent.com/phylum-dev/cli/main/assets/ui-project.webp)
Updated it to read as an optional step

2022-12-02 22:32 UTC, furi0us333 commented on docs/welcome/welcome.md
> +  - The manifest file contains metadata about the extension beyond its executable source code. This allows you to define allowed resources in the sandboxed runtime. All available options can be found
Decided to remove this section as I don't believe Extensions belong on the Welcome page.

2022-12-02 22:53 UTC, furi0us333 commented
Closing this as the work was moved to another repo https://github.com/phylum-dev/documentation/pull/2

2022-12-02 22:53 UTC, closed without merging