docs: Update `phylum group member add` example
phylum-dev/cli pull request #909
Opened 2023-01-12 23:04 UTC by furi0us333

The example was missing the group in the command.

2023-01-12 23:23 UTC, furi0us333 commented
@cd-work Based on the tests failing, I think I am missing something on the proper way to update the docs now that you have the auto-generate. Should I update [this](https://github.com/phylum-dev/cli/blob/main/doc_templates/phylum_group_member_add.md) instead?

2023-01-12 23:36 UTC, cd-work commented
> Should I update [this](https://github.com/phylum-dev/cli/blob/main/doc_templates/phylum_group_member_add.md) instead?

Correct, only the templates itself can ever be edited. More details on this can be found in the readme of the templates directory:
https://github.com/phylum-dev/cli/tree/main/doc_templates

2023-01-12 23:37 UTC, cd-work requested changes
See my latest comment.

2023-01-13 18:55 UTC, maxrake requested changes
To get the tests to pass, there is one more step required: run the `cargo xtask gendocs` command locally and commit the changes that come from that. This process is outlined in the `CONTRIBUTING.md` file, in the Documentation section.

Additionally, it appears the same change made for the `phylum group member add` command doc is needed for the `phylum group member remove` command doc (template).

2023-01-13 21:31 UTC, cd-work submitted a review, later dismissed
Regenerated the documentation, leaving final approval up to @maxrake.

2023-01-13 21:33 UTC, maxrake submitted a review, later dismissed
These changes look good now. However, there may still be more that @furi0us333 was looking to make. At least, he mentioned something to that effect earlier today in a meeting.

2023-01-13 21:44 UTC, maxrake approved these changes

2023-01-13 22:28 UTC, maxrake approved these changes

2023-01-13 22:40 UTC, merged