Fix install with poetry extension
phylum-dev/cli pull request #930
Opened 2023-01-28 00:03 UTC by cd-work

Since the `poetry install` subcommand does not have a `--lock` argument, it would cause the subcommand to fail. Since `install` should generally be based on an updated lockfile already anyway, it should be fine to run an analysis without first updating the lockfile.

However there are options allowing `install` to modify the lockfile, which is why a proper solution would likely involve parsing the `--dry-run` output instead.

2023-01-28 00:09 UTC, cd-work commented
Follow-up issue for a "proper", more complicated fix: https://github.com/phylum-dev/cli/issues/931

2023-01-30 13:46 UTC, andreaphylum approved these changes

2023-01-31 09:35 UTC, cd-work commented
> The extensions/poetry/README.md documentation should be updated to make it more clear that the install command is not currently supported...even if it is only temporary.

But it is supported? It's just *some* subset of the install command that might not run an analysis on the new stuff. And I'm sure that's not the only way to escape analysis.

2023-01-31 15:55 UTC, maxrake commented
> But it is supported? It's just _some_ subset of the install command that might not run an analysis on the new stuff. And I'm sure that's not the only way to escape analysis.

Oh...I see it now! 🤦 
The lockfile is still analyzed before the `install` command is allowed to proceed. I was not paying close enough attention to the code flow...sorry.

2023-01-31 15:56 UTC, maxrake requested changes
The output of running this extension did cause some confusion since it prints `[phylum] Lockfile updated successfully.` for the `install` subcommand...which is misleading b/c that subcommand is excluded from the block of code that does update the lockfile.

It appears maybe this line just needs to be moved up, to go inside the larger block that excludes the `install` subcommand:

```
  console.log(`[${green("phylum")}] Lockfile updated successfully.\n`);
```

2023-01-31 18:46 UTC, maxrake approved these changes
LGTM

2023-01-31 20:10 UTC, louislang approved these changes
lgtm! 🚀

2023-01-31 20:10 UTC, merged